### ISSUE TITLE
Crash reports are not clear and not being symbolicated

### ISSUE THREAD

**Issue by gouravkumar1207** [embrace-io/embrace-apple-sdk#118] opened 2024-11-05 05:00 UTC
**Issue:-**

Previously we were using embrace 5.X version so we found that iOS crashes are not being symbolicated and error reports like Culture Cloud 0x2d300c _mh_execute_header + 2961420 so after this we updated embrace version from 5.x to 6.x but still facing same issue crash reports are not clear and not being symbolicated.

* iOS Version :—— Swift 5, iOS 16, Xcode 16.0
* Embrace SDK Version :——  6.4.2
* Whether you are testing on an emulator or physical device ——— we are facing this issue on production for all users (physical device)

**Comment by ArielDemarco** [comment] 2024-11-05 17:51
Hey @gouravkumar1207, the SDK does not perform offline symbolication; in our case, the symbolication process is handled by the backend. For this, you'll probably need to add some configuration to your project. Have you followed the guides in the documentation related to this? Just in case, here are the links for version [5.x](https://embrace.io/docs/ios/5x/integration/dsym-upload/) and [6.x](https://embrace.io/docs/ios/open-source/getting-started/symbolicating-crash-reports/).

**Comment by gouravkumar1207** [comment] 2024-11-06 04:36
@ArielDemarco but we are manually uploading DSYM file on embrace from setting section ![Image](https://github.com/user-attachments/assets/c8763486-47e7-4c4b-a2ff-6a0f668c2e25)

**Comment by ArielDemarco** [comment] 2024-11-06 16:03
By examining the `dSYM Upload History` and the list of crashes in the `Crashes` menu, I've noticed that **some dSYMs are missing**; specifically, the dSYM UUIDs from `Culture Cloud` and `RealmSwift` appear to be absent for all the crashes. Unless you locate and upload these specific dSYMs, the dashboard wont be able to symbolicate the crashes. Note that when you open a non-symbolicated crash from the `Crashes` menu, you can see a suggestion there to use the `mfind` command to locate those dSYMs on the Mac that performed the build.

That being said, I strongly encourage you to follow the documentation related to automating the symbol upload in your project setup (either if it's 5.x or 6.x). We provide tools so you don't have to manually find dSYMs, which can be particularly challenging if you're uploading your app from a CI environment

**Comment by gouravkumar1207** [comment] 2024-11-06 16:51
![Image](https://github.com/user-attachments/assets/d832694d-ab5a-45d3-9bc6-c7f10c4eb028)
as you can see in attached screen shot embrace showing we have successfully uploaded correct DSYM file corresponding of UUIDs in 5 nov

**Comment by ArielDemarco** [comment] 2024-11-06 18:52
Ok, so digging deeper I found out that there's some sort of weirdness in the `dSYM` file we've got. Considering the issue is related to the dsym and the process dsym uploading (and given its a not an SDK) issue i'm going to close this issue out and reach out to you in the community slack.

**Closed by ArielDemarco** 2024-11-06 18:52 UTC
